# Project Name
TARGET = Tremolo

# Sources
CPP_SOURCES = tremolo.cpp

# Library Locations
LIBDAISY_DIR = ../libDaisy
DAISYSP_DIR = ../DaisySP

# Core location, and generic makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
CFLAGS += -I../Terrarium

